[package]
name = "rep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bio = "1.5.0"
clap = { version = "4.5.2", features = ["cargo"] }
csv = "1.3.0"
